default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_demo_lecture_development

test:
  <<: *default
  database: rails_demo_lecture_test

production:
  <<: *default
  database: rails_demo_lecture_production
  username: rails_demo_lecture
  password: <%= ENV['RAILS_DEMO_LECTURE_DATABASE_PASSWORD'] %>
